POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhcmtuZWJ1bGEiLCJpZCI6IjVmNDE5ODFkMWM5NDA0NjhjNzkzMGY4YiIsImlhdCI6MTU5ODE2NTc5M30.0auXvwCw-6M8DxvF4NWQVhLAd1gN-QFWez19Mk3W9ws

{
    "title": "Single page apps use token authentication",
    "author": "mark",
    "url": "heyhey.com/hey",
    "likes": 100
}